---
dependency:
  name: galaxy
driver:
  name: docker
scenario:
  name: all
  test_sequence:
    - destroy
    - create
    - prepare
    - converge
    - idempotence
    # - verify
    - destroy

platforms:
  - name: system-repo-epel-rocky8
    image: lotusnoir/ansible_molecule_test_images:rocky8
    pre_build_image: true
    cgroupns_mode: host
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    groups:
      - python3
  - name: system-repo-epel-rocky9
    image: lotusnoir/ansible_molecule_test_images:rocky9
    pre_build_image: true
    cgroupns_mode: host
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    groups:
      - python3
  - name: system-repo-epel-oraclelinux8
    image: lotusnoir/ansible_molecule_test_images:oraclelinux8
    pre_build_image: true
    cgroupns_mode: host
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    groups:
      - python3
  - name: system-repo-epel-oraclelinux9
    image: lotusnoir/ansible_molecule_test_images:oraclelinux9
    pre_build_image: true
    cgroupns_mode: host
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    groups:
      - python3

provisioner:
  name: ansible
  connection_options:
    ansible_remote_tmp: /tmp
    ansible_python_interpreter: auto_silent
  config_options:
    defaults:
      roles_path: "$MOLECULE_PROJECT_DIRECTORY/.."
      callbacks_enabled: timer, profile_tasks, profile_roles
      verbosity: 3
      forks: 20
      host_key_checking: false
    ssh_connection:
      pipelining: true
      ssh_args: -o ControlMaster=auto -o ControlPersist=600s
  log: true
  playbooks:
    prepare: prepare.yml
    converge: playbook.yml
  inventory:
    group_vars:
      python3:
        ansible_python_interpreter: /usr/bin/python3
    host_vars:
      bullseye:
        ansible_python_interpreter: "/usr/bin/python3.9"
      bookworm:
        ansible_python_interpreter: "/usr/bin/python3.9"

verifier:
  name: ansible
