---
- name: Verify
  hosts: all
  gather_facts: true
  any_errors_fatal: true
  tasks:
    - name: "Verify tasks"
      when: not (ansible_os_family in ['RedHat', 'Rocky', 'OracleLinux'] and ansible_distribution_major_version == '8')
      block:


